<?php

namespace CM\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LinkUserClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkUserClientRepository extends EntityRepository
{
}
